### ISSUE TITLE
Create endpoints related to 'notifications' and 'groups'

### ISSUE THREAD

**Issue by cjchirag7** [Cyber-Labs/cl-judge#32]
### Notifications

Create a table `notifications` with the following fields -
- id (primary key)
- heading
- description (optional)
- created_at
- link

Create a table `user_notifications` with the following fields -

The above table will contain mappings between user and notifications.
- id (primary key)
- username (foreign key from user table)
- notification_id (foreign key from notification table)

The below endpoints would be available to all the users -
- `GET '/notifications?limit=3'` : Get the most recent 3 notifications of the user
- `GET '/notifications'` : Get all the notifications for the user 

- Frontend would provide only `access_token` of the user in request

### Groups

Create a table `groups` with the following fields -
- id (primary key)
- name
- confidential (boolean)
- creator (username of the creator of group, as there can be multiple admins in a particular group)
- member_count (number of members of that group)

Create a table `user_groups` with the following fields -
- id (primary key)
- username (foreign key from user table)
- group_id (foreign key from group table)
- admin (boolean)
The above table will contain many-to-many mappings of user and groups.

These endpoints would only be accessible to admins only -
- `GET /groups/admin-groups` - Returns a list of all (both confidential and non-confidential) the groups in which the user is present as an `admin`. This should contain name, creator and member_count of the groups. 
- `POST /groups/add-group` - Frontend would send `name` for group, `confidential` (boolean) and `usernames` ( a JSON array of usernames to be added in that group ). The array may be empty
- `POST groups/:group-id/add-members` - Frontenend would send a JSON array of usernames to be added in the group with id as `group-id`
- `POST groups/:group-id/make-admin` - Frontend would send a `username` who should be made an admin (  A group admin can create more group admins or remove group admins, except the creator of the group)
- `POST groups/:group-id/remove-admin` - Frontend would send a `username` who should be removed from admin
- `POST groups/:group-id/update-name` - Frontend would send new `name` for the group, which should be updated.
- `POST groups/:group-id/add-branch` - Frontend would send a branch code and a department code. Users who are having those branch code and department code and not present in the group already, should be added to the group

These endpoints would be accessible to all users -
- `GET /groups` - Returns a list of all `non-confidential` groups in which the user is present (not necessary, as admin)
- `GET /groups/:group-id` - Returns group name and a list of members of the group. Each member object have the fields - Full Name, username, admin (boolean), profileImg . Note : For non-admins, these information would be accessible only if the group is not confidential.

The frontend would need to provide the `access_token` of user in the header of each of the requests

**Note** : Once, tables and endpoints for both `notifications` and `groups` have been created, make sure that following notifications are generated automatically : 
1. When users are added to a `non-confidential` group, they must receive a notification : 
```
{ heading : 'Added to group ${group-name}',
description: `You have been added to the group ${group-name}` ,
created_at: "timestamp of the notification",
link: 'http://${FRONTEND_HOST}:${FRONTEND_PORT}/groups/${group-id}'}
```

2. When a user is added as an admin, he must receive a notification : 
```
{ heading : 'Promoted to admin of ${group-name}',
description: `You have been promoted to admin in the group ${group-name}` ,
created_at: "timestamp of the notification",
link: 'http://${FRONTEND_HOST}:${FRONTEND_PORT}/groups/${group-id}'}
```

3. When a user is removed from an admin, he must receive a notification : 
```
{ heading : 'Removed from admin of ${group-name}',
description: `You have been removed from admin in the group ${group-name}` ,
created_at: "timestamp of the notification",
link: 'http://${FRONTEND_HOST}:${FRONTEND_PORT}/groups/${group-id}'}
```

Suggestions for changes are welcome.

**Comment by cjchirag7** [comment]
@ridhishjain , please verify this plan for `notifications` and `groups` and mention, if any changes / clarifications are required.

**Comment by ridhishjain** [comment]
@cjchirag7 As far as I understood,

`groups` table will be specific for groups and will contain main info for all groups... each group will be mapped to a unique id.

`user_groups` will be like if I am enrolled in 3 groups say, then there will be 3 rows in the table corresponding to me for each of the groups... right?

**Comment by ridhishjain** [comment]
> * `GET /admin-groups` - Returns a list of all (both confidential and non-confidential) the groups in which the user is present as an `admin`. This should contain name, creator and member_count of the groups.

shouldn't it be `GET/groups/admin-groups/:username`? Sending username along with `access-token` because only token won't suffice. Searching that user in db requires username

**Comment by ridhishjain** [comment]
### 1.

> * `GET /admin-groups` - Returns a list of all (both confidential and non-confidential) the groups in which the user is present as an `admin`. This should contain name, creator and member_count of the groups.

It should be `GET /groups/admin-groups ? 
Sending username along with access-token is necessary because only token won't suffice. Searching that user in db requires username

___

### 2.

> * `POST /add-group` - Frontend would send `name` for group and `usernames` ( a JSON array of usernames to be added in that group ). The array may be empty

I think this should also be `POST /groups/add-group` for uniformity in APIs. Along with group name and users array, would it also send creator and confidential?
```
name: string
confidential: boolean,
creator: string,
users: [
    {username: string, isAdmin: boolean},
    {username: string, isAdmin: boolean}
]
```
The info related to creator and group name will be added to `groups` table and the info of users in the array will be stored in `user_groups` table....that right?

___

### 3.

> * `POST groups/:group-id/add-group-member` - Frontenend would send a JSON array of usernames to be added in the group with id as `group-id`

`POST groups/:group-id/add-member` add member instead of add-group-member, too long!
The array should be of objects, just like above, so that the count in `groups` table will be changed and all the users in the array will be added to `user_groups` table.
```
users: [
    {username: string, isAdmin: boolean},
    {username: string, isAdmin: boolean}
]
```

___

### 4.

> * `POST groups/:group-id/make-admin` - Frontend would send a `username` who should be made an admin (  A group admin can create more group admins or remove group admins, except the creator of the group)
> * `POST groups/:group-id/remove-admin` - Frontend would send a `username` who should be removed from admin
> * `POST groups/:group-id/update-name` - Frontend would send new `name` for the group, which should be updated.
> * `POST groups/:group-id/add-branch` - Frontend would send a branch code and a department code. Users who are having 
those branch code and department code and not present in the group already, should be added to the group

These seems fine!!

___

### 5.

>These endpoints would be accessible to all users -
> * `GET /groups` - Returns a list of all `non-confidential` groups in which the user is present (not necessary, as admin)
> * `GET /groups/:group-id` - Returns group name and a list of members of the group. Each member object have the fields - Full Name, username, admin (boolean), profileImg . Note : For non-admins, these information would be accessible only if the group is not confidential.

Seems fine!!!

___

### 6.

> The frontend would need to provide the `access_token` of user in the header of each of the requests

Username too, along with access token, as searching DB for a user requires username

**Comment by cjchirag7** [comment]
> @cjchirag7 As far as I understood,
> 
> `groups` table will be specific for groups and will contain main info for all groups... each group will be mapped to a unique id.
> 
> `user_groups` will be like if I am enrolled in 3 groups say, then there will be 3 rows in the table corresponding to me for each of the groups... right?

Yes, you got it right !

**Comment by cjchirag7** [comment]
@ridhishjain , I have changed the names of endpoints. I wish to confirm one thing, whether it is possible to decode the username of the user in backend itself, using the access_token ?

**Comment by cjchirag7** [comment]
___

### 3.

> * `POST groups/:group-id/add-group-member` - Frontenend would send a JSON array of usernames to be added in the group with id as `group-id`

`POST groups/:group-id/add-member` add member instead of add-group-member, too long!
The array should be of objects, just like above, so that the count in `groups` table will be changed and all the users in the array will be added to `user_groups` table.
```
users: [
    {username: string, isAdmin: boolean},
    {username: string, isAdmin: boolean}
]
```

___

In DB, we can set isAdmin default to be false. So, sending just the array of usernames should be enough, I guess.
An example of users array, to be sent in request

```
"["chirag","ridhish","sample"]"
```

In backend, JSON.parse() can be used to obtain the JS array of usernames -

```
["chirag", "ridhish", "sample"]
```

What's your opinion on this ?

**Comment by ridhishjain** [comment]
1. username is to be decoded via an access token, no need to give in API!
2. By default, isAdmin will be false... for making admin, call `make-admin` API separately!

**Comment by ridhishjain** [comment]
Closing as a tracker issue is made for the same - #37
