### ISSUE TITLE
Schemas

### ISSUE THREAD

**Issue by ridhishjain** [Cyber-Labs/cl-judge#68]
### Contests

- [x] **`POST /contests/`**: createContest
- [x] **`POST /contests/:contest_id/moderator`**: addModerator
- [x] **`DELETE /contests/:contest_id/moderator`**: removeModerator
Not needed:
- [x] **`POST /contests/:contest_id/participate`**: participate
- [x] **`POST /contests/:contest_id/update`**: updateContest
- [x] **`GET /contests?active=true&past=true&upcoming=true&limit=3&offset=5`**: getContests
- [x] **`GET /contests/moderator_contests?limit=3&offset=5`**: getModeratorContests
- [x] **`GET /contests/:contest_id`**: getContest
- [x] **`GET /contests/:contest_id/moderators`**: getContestModerators
- [x] **`GET /contests/:contest_id/questions`**: getAllQuestions
- [x] **`GET /contests/:contest_id/questions/:question_id`**: getQuestion
- [x] **`GET /contests/:contest_id/participants`**: getAllParticipants
- [x] **`GET /contests/:contest_id/participants?details=true`**: getAllParticipantsDetails
- [x] **`GET /contests/:contest_id/leaderboard`**: getLeaderboard
- [x] **`GET /contests/:contest_id/questions/:question_id/leaderboard`**: getQuestionLeaderboard

### Questions:

- [x] **`POST /questions/`**: createQuestion
- [x] **`GET /questions/moderator_questions?limit=5&search=’’`**: getModeratorQuestions
- [x] **`GET /questions/:question_id`**: to get the question
- [x] **`POST /questions/:question_id/update`, Editor only**: to edit the questions, the change will be reflected in all instances of the question
- [x] **`GET /questions/`**:  - send all public questions with their contest_id (for practice section) 
- [x] **`POST /questions/:question_id/editor` Editor only**: Add editor to a question
- [x] **`DELETE /questions/:question_id/editor` Editor only**: Remove editor to a question (creator can't be removed)
- [x] **`POST /questions/:question_id/fork` Editor only**: Return the id of the forked new question

### Submissions

- [x] **`POST /contest/:contest_id/questions/:question_id/submit`**: createSubmission
Not needed:
- [x] **`GET /contest/:contest_id/submissions/:submission_id`**: getSubmission
- [x] **`GET /contest/:contest_id/submissions?user=username`**: getAllUserSubmissions
- [x] **`GET /contest/:contest_id/submissions`**: getAllSubmissions

### Tags

- [x] **`POST /tag`**: createTag
Not needed:
- [x] **`GET /tags?search=keyword`**: getTags

**Comment by NBNARADHYA** [comment]
@ridhishjain  I think there is a problem with MD

**Comment by NBNARADHYA** [comment]
@ridhishjain  Just check all related to questions

**Comment by ridhishjain** [comment]
all schemas done, closing!!
